Number of various updates for reliability

diff --git a/etc/scripts/awscreds-n-leftovers b/etc/scripts/awscreds-n-leftovers
--- a/etc/scripts/awscreds-n-leftovers
+++ b/etc/scripts/awscreds-n-leftovers
@@ -6,6 +6,7 @@
 # dont do anything if process is already running
 if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
     echo "[WARN] Process of ${0} is already running"
+    logger -i -t awscreds-n-leftovers "[WARN] Process of ${0} is already running"
     exit
 fi
 
@@ -20,14 +21,18 @@ LAPSEDIR=$(jq -r .maindir <<< $CONFIG)
 s3bucket="s3://"$(jq -r .aws.s3 <<< $CONFIG)
 maindir=$(jq -r .maindir <<< $CONFIG)
 
+
 # take care of timelapses
-aws s3 mv $LAPSEDIR/dailytimelapses $s3bucket/dailytimelapses --exclude "*" --include "*.mp4" --recursive \
-    --page-size 1 --acl "public-read" 2>&1 | logger -i -t awscreds-n-leftovers
+# only past 1AM
+if [ $(date +"%H") -ge 1 ]; then
+    aws s3 mv $LAPSEDIR/dailytimelapses $s3bucket/dailytimelapses --recursive \
+        --exclude "*" --include "*.mp4"  --page-size 1 --acl public-read \
+        2>&1 | logger -i -t awscreds-n-leftovers
 
-if [ $? -ne 0 ]; then
-    logger -t awscreds-n-leftovers "[WARN] AWSCLI error code: $?"
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        logger -t awscreds-n-leftovers "[WARN] AWSCLI error code: $?"
+    fi
 fi
-
 # take care of some failed files
 find $maindir -name 'aws*.retry' -exec /etc/scripts/retry-files {} \;
 
diff --git a/etc/scripts/retry-files b/etc/scripts/retry-files
--- a/etc/scripts/retry-files
+++ b/etc/scripts/retry-files
@@ -7,20 +7,25 @@ if [ ! -f $1 ]; then
     echo "[ERR] File $1 does not exist. Cannot continue."
 fi
 
-CONFIG=$(cat /etc/rpi.json)
+CONFIG-$(cat /etc/rpi.json)
 maindir=$(jq -r .maindir <<< $CONFIG)
 filename=$(basename $1)
 
-logger -t retry-files "Taking file $1"
+logger -ti retry-files "Taking file $1"
 mv -fv $1 /tmp/ | logger -t retry-files
 
 # now iterate through the file
+oks=0;errs=0
 while IFS='' read -r line || [[ -n "$line" ]]; do
     eval $line
     if [ $? -ne 0 ]; then
+        logger -ti retry-files "[ERR:$?] $line"
         echo $line >> "$maindir/$filename"
-        logger -t retry-files "[ERR] $line"
+        errs=$(($errs+1))
     else
-        logger -t retry-files "[OK] $line"
+        logger -ti retry-files "[OK] $line"
+        oks=$(($oks+1))
     fi
 done < "/tmp/$filename"
+
+logger -ti retry-files "Summary: successfully retried $oks command(s). Failed $errs"
