Some overhaul + system-status script added

diff --git a/etc/scripts/awscreds-n-leftovers b/etc/scripts/awscreds-n-leftovers
--- a/etc/scripts/awscreds-n-leftovers
+++ b/etc/scripts/awscreds-n-leftovers
@@ -1,19 +1,18 @@
 #!/bin/bash
 
-# quick access to this on AWSlOGS:
-# https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logEventViewer:group=/var/log/messages;filter=%22awscreds-n-leftovers%22;start=PT1H
-
 # dont do anything if process is already running
 if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
     echo "[WARN] Process of ${0} is already running"
-    logger -i -t awscreds-n-leftovers "[WARN] Process of ${0} is already running"
+    logger -i -t $loggertitle "[WARN] Process of ${0} is already running"
     exit
 fi
 
-rm -fv /root/.aws/credentials | logger -i -t awscreds-n-leftovers
+loggertitle="$(basename ${0})[$$]"
+
+rm -fv /root/.aws/credentials | logger -i -t $loggertitle
 service amazon-ssm-agent restart
 service awslogs restart
-logger -i -t awscreds-n-leftovers "Reloaded amazon-ssm-agent and awslogs"
+logger -i -t $loggertitle "Reloaded amazon-ssm-agent and awslogs"
 
 # do some leftovers
 CONFIG=$(cat /etc/rpi.json)
@@ -21,19 +20,41 @@ LAPSEDIR=$(jq -r .maindir <<< $CONFIG)
 s3bucket="s3://"$(jq -r .aws.s3 <<< $CONFIG)
 maindir=$(jq -r .maindir <<< $CONFIG)
 
-
-# take care of timelapses
-# only past 1AM
-if [ $(date +"%H") -ge 1 ] && [ $(date +"%H") -lt 5 ]; then
-    aws s3 mv $LAPSEDIR/dailytimelapses $s3bucket/dailytimelapses --recursive \
-        --exclude "*" --include "*.mp4"  --page-size 1 --acl public-read \
-        2>&1 | logger -i -t awscreds-n-leftovers
-
-    if [ ${PIPESTATUS[0]} -ne 0 ]; then
-        logger -t awscreds-n-leftovers "[WARN] AWSCLI error code: $?"
-    fi
-fi
 # take care of some failed files
 find $maindir -name 'aws*.retry' -exec /etc/scripts/retry-files {} \;
 
-# TODO cleanup from some old temporary files
+# take care of timelapses
+DATEDIR=`date +%Y/%m/%d`
+CAM="cam1" # TODO make this dynamic from rpi.json
+TMPLOCAL="$maindir/$CAM/$DATEDIR"
+
+# make timelapse for yesterday
+if [ $(date +"%H") -eq 1 ]; then
+    /etc/scripts/create-timelapse $CAM
+fi
+
+# move to S3 only in the hours from 1 to 5 AM
+if [ $(date +"%H") -ge 1 ] && [ $(date +"%H") -lt 5 ]; then
+    aws s3 mv $LAPSEDIR/dailytimelapses $s3bucket/dailytimelapses --recursive \
+        --exclude "*" --include "*.mp4"  --page-size 1 --acl public-read \
+        2>&1 | logger -i -t $loggertitle
+
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        logger -t $loggertitle "[WARN] AWSCLI error code: ${PIPESTATUS[0]}"
+    fi
+fi
+
+# delete old *.retry files
+find /tmp -mtime -1 -type f -name "*.retry" -delete
+
+# delete old *.jpg files
+find $maindir -mtime -10 -type f -name "*.jpg" -delete
+
+# delete old timelapses
+find $maindir -mtime -20 -type f -name "*.mp4" -delete
+
+# wipe old temporary files
+find $maindir -mtime -10 -type f -name 'awscli-n-logs-updated.tmp' -delete
+
+# delete empty dirs
+find $maindir -mtime -10 -type d -empty -delete
diff --git a/etc/scripts/capture-image b/etc/scripts/capture-image
--- a/etc/scripts/capture-image
+++ b/etc/scripts/capture-image
@@ -6,6 +6,7 @@ if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
     exit
 fi
 
+loggertitle="$(basename ${0})[$$]"
 FILENAME=`date +%Y%m%d%H%M%S`
 DATEDIR=`date +%Y/%m/%d`
 RETRYDATE=`date +%Y%m%d`
@@ -20,10 +21,10 @@ jq_temp=$(jq -r .weather.jq_temp <<< $CONFIG)
 jq_wind=$(jq -r .weather.jq_wind <<< $CONFIG)
 
 if [ -z "$CAM" ]; then
-    echo "ERROR: Please specify \$1 parameter. Typically this is 'cam1'"
+    echo "ERROR: Please specify \$1 parameter (for eg. cam1)"
     exit
 fi
-RTSP=$(jq -r .$CAM.rtsp <<< $CONFIG)
+
 s3bucket="s3://"$(jq -r .aws.s3 <<< $CONFIG)"/$CAM"
 
 if [ -z "$SUNFILE" ]; then
@@ -42,44 +43,56 @@ sunset=`date +"%H%M%S" --date="$(jq -r .results.sunset <<< $SUNFILE) $setoffset"
 NOW=$(date +"%H%M%S")
 
 if [ $NOW -ge $sunrse ] && [ $NOW -le $sunset ]; then
-    ffmpeg="ffmpeg -rtsp_transport tcp -i $RTSP \
-        -timeout 30 -vframes 1 -r 1 -q:v 5 $TMPLOCAL/$FILENAME.jpg"
-    logger -t capture-image "> $ffmpeg"
-    eval $ffmpeg 2>&1 | logger -t capture-image
+    takecmd=$(jq -r .$CAM.takecmd <<< $CONFIG)
+    takecmd=$(printf "$takecmd" "/tmp/$CAM-$FILENAME-1.jpg")
+    logger -i -t $loggertitle "> $takecmd"
+    eval $takecmd 2>&1 | logger -i -t $loggertitle
 
-    if [ ${PIPESTATUS[0]} -eq 0 ]; then
+    # todo: test content. If not JPG reboot the cam
+    # curl -X PUT "http://IPADDRESS/cgi-bin/api.cgi?cmd=reboot&code=0&user=username&password=password"
+    if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        logger -i -t $loggertitle "[ERR] Failed to take image from $CAM"
+    else
         sleep 3 # wait a bit
 
         # now annotate with temperature
-        TEMP=$(jq -rc "$jq_temp" < $maindir/weather.json)
-        convert $TMPLOCAL/$FILENAME.jpg -font Courier -pointsize 65 -gravity southwest \
-            -fill white -annotate 0 $TEMP -quality 60 /tmp/$FILENAME.jpg \
-            2>&1 | logger -t capture-image
+        temp=$(jq -rc "$jq_temp" < $maindir/weather.json)
+        wind=$(jq -rc "$jq_wind" < $maindir/weather.json)
+        annotateformat=$(jq -r .$CAM.annotateformat <<< $CONFIG)
+        annotateformat=$(printf "$annotateformat" "$temp" "$CAM")
+        annotatecmd=$(jq -r .$CAM.annotatecmd <<< $CONFIG)
+        annotatecmd=$(printf "$annotatecmd" "/tmp/$CAM-$FILENAME-1.jpg" "$annotateformat" "/tmp/$CAM-$FILENAME-2.jpg")
+        logger -i -t $loggertitle "> $annotatecmd"
+        eval $annotatecmd 2>&1 | logger -i -t $loggertitle
 
         if [ ${PIPESTATUS[0]} -eq 0 ]; then
-            # replace original file with annotated one
-            mv -f /tmp/$FILENAME.jpg  $TMPLOCAL/
+            # place annotated image into correct place
+            mv -fv /tmp/$CAM-$FILENAME-2.jpg $TMPLOCAL/$FILENAME.jpg | logger -i -t $loggertitle
         else
-            logger -t capture-image "[WARN] Annotation failed. IM convert exit code: ${PIPESTATUS[0]}"
-            rm -f /tmp/$FILENAME.jpg
+            logger -i -t $loggertitle "[WARN] Annotation failed. IM convert exit code: ${PIPESTATUS[0]}"
         fi
+        # remove residual tmp files
+        rm -fv /tmp/$CAM-$FILENAME-*.jpg | logger -i -t $loggertitle
 
         # now upload to s3
         # requires S3 PutObject and PutObjectAcl permissions
         aws s3 cp $TMPLOCAL/$FILENAME.jpg $s3bucket/$DATEDIR/ \
-            --acl "public-read" 2>&1 | logger -t capture-image
+            --acl "public-read" 2>&1 | logger -i -t $loggertitle
 
         if [ ${PIPESTATUS[0]} -eq 0 ]; then
             aws s3 cp "$s3bucket/$DATEDIR/$FILENAME.jpg" "$s3bucket/current.jpg" \
-                --acl "public-read" 2>&1 | logger -t capture-image
+                --acl "public-read" 2>&1 | logger -i -t $loggertitle
         else
-            logger -t capture-image "[WARN] AWSCLI error code: $?"
-            echo "aws s3 cp $TMPLOCAL/$FILENAME.jpg $s3bucket/$DATEDIR/ --acl public-read" \
-                >> $maindir/aws-s3-cp-$RETRYDATE.retry
-            logger -t capture-image "[WARN] $maindir/aws-s3-cp-$RETRYDATE.retry file written"
+            logger -i -t $loggertitle "[WARN] AWSCLI failed"
+            if [ -f $TMPLOCAL/$FILENAME.jpg ]; then
+                echo "aws s3 cp $TMPLOCAL/$FILENAME.jpg $s3bucket/$DATEDIR/ --acl public-read" \
+                    >> $maindir/aws-s3-cp-$RETRYDATE.retry
+                logger -i -t $loggertitle "[WARN] $maindir/aws-s3-cp-$RETRYDATE.retry file written"
+            else
+                logger -i -t $loggertitle "[WARN] File $TMPLOCAL/$FILENAME.jpg does not exist"
+            fi
         fi
     fi
 else
     echo "Goodnight"
-    /etc/scripts/create-timelapse $CAM $TMPLOCAL $maindir/aws-s3-cp-$RETRYDATE.retry
 fi
diff --git a/etc/scripts/create-timelapse b/etc/scripts/create-timelapse
--- a/etc/scripts/create-timelapse
+++ b/etc/scripts/create-timelapse
@@ -9,57 +9,47 @@ if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
     exit
 fi
 
-CONFIG=$(cat /etc/rpi.json)
-CAM=${1,,} # always lower case ($1 param)
-ALLJPEGS=$2
-RETRYFILE=$3
-LAPSEFILE=$CAM"_$(date +%Y%m%d).mp4"
-LAPSEDIR=$(jq -r .maindir <<< $CONFIG)"/dailytimelapses"
-
-if [ -z "$CAM" ]; then
+if [ -z "$1" ]; then
     echo "[ERR] Please specify \$1 parameter. Typically this is 'cam1'"
     exit
 fi
 
-# delete empty dirs
-find $ALLJPEGS -type d -empty -delete
+loggertitle="$(basename ${0})[$$]"
+CONFIG=$(cat /etc/rpi.json)
+CAM=${1,,} # always lower case ($1 param)
+if [ ! -z "$2" ]; then
+    DATEDIR=$(date +%Y/%m/%d --date="$2")
+    LAPSEFILE="${CAM}_$(date +%Y%m%d --date="$2").mp4"
+else
+    DATEDIR=$(date +%Y/%m/%d --date="yesterday 13:00")
+    LAPSEFILE="${CAM}_$(date +%Y%m%d --date="yesterday 13:00").mp4"
+fi
+maindir=$(jq -r .maindir <<< $CONFIG)
+ALLJPEGS="$maindir/$CAM/$DATEDIR"
+LAPSEDIR="$maindir/dailytimelapses"
 
-if [ -z "$ALLJPEGS" ] || [ ! -d $ALLJPEGS ]; then
-    echo "[ERR] Please specify \$2 parameter with full path where *.jpg files resides. Directory must be not empty."
+if [ ! -d $ALLJPEGS ]; then
+    echo "[ERR] Directory $ALLJPEGS does not exist or you provided incorrect \$1 and \$2 parameters"
     exit
 fi
 
 if [ ! -d $LAPSEDIR ]; then
-    mkdir -v -p $LAPSEDIR
-fi
-
-if [ -f "$LAPSEDIR/$LAPSEFILE" ]; then
-    echo "[WARN] Timelapse $LAPSEDIR/$LAPSEFILE file already exist"
-    exit
-fi
-
-if [ -f "/tmp/$LAPSEFILE" ]; then
-    echo "[WARN] Timelapse /tmp/$LAPSEFILE file already exist"
-    exit
+    mkdir -v -p $LAPSEDIR | logger -i -t $loggertitle
 fi
 
 # if we are here we are good to make a timelapse!
-logger -i -t create-timelapse "> /etc/scripts/create-timelapse $CAM $ALLJPEGS"
+ffmpeg="ionice -c2 -n 5 ffmpeg -r 24 -pattern_type glob -i \"$ALLJPEGS/*.jpg\" \
+    -s hd1080 -vcodec libx264 -pix_fmt yuvj420p /tmp/$LAPSEFILE -y"
+logger -i -t $loggertitle "> $ffmpeg"
 
-ffmpeg -r 24 -pattern_type glob -i "$ALLJPEGS/*.jpg" \
-    -s hd1080 -vcodec libx264 "/tmp/$LAPSEFILE" -y
+eval $ffmpeg
 
-if [ $? -eq 0 ]; then
-    mv -fv "/tmp/$LAPSEFILE" "$LAPSEDIR/$LAPSEFILE" | logger -i -t create-timelapse
-    logger -i -t create-timelapse "[OK] $LAPSEDIR/$LAPSEFILE"
-    # will move to S3 with separate script
-    # if no $RETRYFILE we are good to wipe the dir!
-    if [ ! -z "$RETRYFILE" ] && [ ! -f $RETRYFILE ]; then
-        rm -fv "$ALLJPEGS/*.jpg" 2>&1 | logger -i -t create-timelapse
-    else
-        logger -i -t create-timelapse "[WARN] $RETRYFILE contains images not synced to S3."
-    fi
+if [ ${PIPESTATUS[0]} -eq 0 ]; then
+    mv -fv /tmp/$LAPSEFILE $LAPSEDIR/$LAPSEFILE | logger -i -t $loggertitle
+    logger -i -t $loggertitle "[OK] $LAPSEDIR/$LAPSEFILE"
+    # now wipe the dir!
+    rm -fr $ALLJPEGS 2>&1 | logger -i -t $loggertitle
 else
-    logger -i -t create-timelapse "[ERR] Failed to create $LAPSEDIR/$LAPSEFILE timelapse. FFMPEG exit code: $?"
-    rm -fv "$LAPSEDIR/$LAPSEFILE" 2>&1 | logger -i -t create-timelapse
+    logger -i -t $loggertitle "[ERR] Failed to create $LAPSEDIR/$LAPSEFILE timelapse. FFMPEG exit code: $?"
+    rm -fv "/tmp/$LAPSEFILE" 2>&1 | logger -i -t $loggertitle
 fi
