Another round of bugfixes and improvements

diff --git a/etc/scripts/awscreds-n-leftovers b/etc/scripts/awscreds-n-leftovers
--- a/etc/scripts/awscreds-n-leftovers
+++ b/etc/scripts/awscreds-n-leftovers
@@ -1,22 +1,21 @@
 #!/bin/bash
 
+loggertitle="$(basename ${0})[$$]"
+
 # dont do anything if process is already running
 if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
-    echo "[WARN] Process of ${0} is already running"
-    logger -i -t $loggertitle "[WARN] Process of ${0} is already running"
+    echo "[ERR] Process of ${0} is already running"
+    logger -t $loggertitle "[ERR] Process of ${0} is already running"
     exit
 fi
 
-loggertitle="$(basename ${0})[$$]"
-
-rm -fv /root/.aws/credentials | logger -i -t $loggertitle
+rm -fv /root/.aws/credentials | logger -t $loggertitle
 service amazon-ssm-agent restart
 service awslogs restart
-logger -i -t $loggertitle "Reloaded amazon-ssm-agent and awslogs"
+logger -t $loggertitle "Reloaded amazon-ssm-agent and awslogs"
 
 # do some leftovers
 CONFIG=$(cat /etc/rpi.json)
-LAPSEDIR=$(jq -r .maindir <<< $CONFIG)
 s3bucket="s3://"$(jq -r .aws.s3 <<< $CONFIG)
 maindir=$(jq -r .maindir <<< $CONFIG)
 
@@ -27,34 +26,36 @@ find $maindir -name 'aws*.retry' -exec /etc/scripts/retry-files {} \;
 DATEDIR=`date +%Y/%m/%d`
 CAM="cam1" # TODO make this dynamic from rpi.json
 TMPLOCAL="$maindir/$CAM/$DATEDIR"
+HOUR=$(date +"%H")
 
 # make timelapse for yesterday
-if [ $(date +"%H") -eq 1 ]; then
+if [ $HOUR -eq 1 ]; then
     /etc/scripts/create-timelapse $CAM
 fi
 
 # move to S3 only in the hours from 1 to 5 AM
-if [ $(date +"%H") -ge 1 ] && [ $(date +"%H") -lt 5 ]; then
-    aws s3 mv $LAPSEDIR/dailytimelapses $s3bucket/dailytimelapses --recursive \
-        --exclude "*" --include "*.mp4"  --page-size 1 --acl public-read \
-        2>&1 | logger -i -t $loggertitle
+if [ $HOUR -ge 1 ] && [ $HOUR -lt 5 ] && [ -d $maindir/dailytimelapses ]; then
+
+    find $maindir/dailytimelapses -type f -name "*.mp4" -exec \
+        aws s3 mv {} $s3bucket/dailytimelapses --acl public-read --only-show-errors \; \
+        2>&1 | logger -t $loggertitle
 
     if [ ${PIPESTATUS[0]} -ne 0 ]; then
-        logger -t $loggertitle "[WARN] AWSCLI error code: ${PIPESTATUS[0]}"
+        logger -t $loggertitle "[ERR] AWSCLI error code: ${PIPESTATUS[0]}"
+    else
+        logger -t $loggertitle "[OK] $LAPSEDIR/dailytimelapses files moved to S3"
+        touch $LAPSEDIR/dailytimelapses/never.empty
     fi
+
 fi
 
 # delete old *.retry files
-find /tmp -mtime -1 -type f -name "*.retry" -delete
-
+find /tmp -mtime +1 -type f -name "*.retry" -exec rm -vf {} \; | logger -t $loggertitle
 # delete old *.jpg files
-find $maindir -mtime -10 -type f -name "*.jpg" -delete
-
+find $maindir -mtime +10 -type f -name "*.jpg" -exec rm -vf {} \; | logger -t $loggertitle
 # delete old timelapses
-find $maindir -mtime -20 -type f -name "*.mp4" -delete
-
+find $maindir -mtime +20 -type f -name "*.mp4" -exec rm -vf {} \; | logger -t $loggertitle
 # wipe old temporary files
-find $maindir -mtime -10 -type f -name 'awscli-n-logs-updated.tmp' -delete
-
+find $maindir -mtime +10 -type f -name "awscli-n-logs-updated.tmp" -exec rm -vf {} \; | logger -t $loggertitle
 # delete empty dirs
-find $maindir -mtime -10 -type d -empty -delete
+find $maindir -mtime +1 -mindepth 1 -type d -empty -exec rm -vrf {} \; | logger -t $loggertitle
diff --git a/etc/scripts/capture-image b/etc/scripts/capture-image
--- a/etc/scripts/capture-image
+++ b/etc/scripts/capture-image
@@ -2,11 +2,12 @@
 
 # dont do anything if process is already running
 if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
-    echo "[WARN] Process of ${0} is already running"
+    echo "[ERR] Process of ${0} is already running"
     exit
 fi
 
 loggertitle="$(basename ${0})[$$]"
+
 FILENAME=`date +%Y%m%d%H%M%S`
 DATEDIR=`date +%Y/%m/%d`
 RETRYDATE=`date +%Y%m%d`
@@ -45,13 +46,13 @@ NOW=$(date +"%H%M%S")
 if [ $NOW -ge $sunrse ] && [ $NOW -le $sunset ]; then
     takecmd=$(jq -r .$CAM.takecmd <<< $CONFIG)
     takecmd=$(printf "$takecmd" "/tmp/$CAM-$FILENAME-1.jpg")
-    logger -i -t $loggertitle "> $takecmd"
-    eval $takecmd 2>&1 | logger -i -t $loggertitle
+    logger -t $loggertitle "> $takecmd"
+    eval $takecmd 2>&1 | logger -t $loggertitle
 
     # todo: test content. If not JPG reboot the cam
     # curl -X PUT "http://IPADDRESS/cgi-bin/api.cgi?cmd=reboot&code=0&user=username&password=password"
     if [ ${PIPESTATUS[0]} -ne 0 ]; then
-        logger -i -t $loggertitle "[ERR] Failed to take image from $CAM"
+        logger -t $loggertitle "[ERR] Failed to take image from $CAM"
     else
         sleep 3 # wait a bit
 
@@ -62,34 +63,34 @@ if [ $NOW -ge $sunrse ] && [ $NOW -le $sunset ]; then
         annotateformat=$(printf "$annotateformat" "$temp" "$CAM")
         annotatecmd=$(jq -r .$CAM.annotatecmd <<< $CONFIG)
         annotatecmd=$(printf "$annotatecmd" "/tmp/$CAM-$FILENAME-1.jpg" "$annotateformat" "/tmp/$CAM-$FILENAME-2.jpg")
-        logger -i -t $loggertitle "> $annotatecmd"
-        eval $annotatecmd 2>&1 | logger -i -t $loggertitle
+        logger -t $loggertitle "> $annotatecmd"
+        eval $annotatecmd 2>&1 | logger -t $loggertitle
 
         if [ ${PIPESTATUS[0]} -eq 0 ]; then
             # place annotated image into correct place
-            mv -fv /tmp/$CAM-$FILENAME-2.jpg $TMPLOCAL/$FILENAME.jpg | logger -i -t $loggertitle
+            mv -fv /tmp/$CAM-$FILENAME-2.jpg $TMPLOCAL/$FILENAME.jpg | logger -t $loggertitle
         else
-            logger -i -t $loggertitle "[WARN] Annotation failed. IM convert exit code: ${PIPESTATUS[0]}"
+            logger -t $loggertitle "[WARN] Annotation failed. IM convert exit code: ${PIPESTATUS[0]}"
         fi
         # remove residual tmp files
-        rm -fv /tmp/$CAM-$FILENAME-*.jpg | logger -i -t $loggertitle
+        rm -fv /tmp/$CAM-$FILENAME-*.jpg | logger -t $loggertitle
 
         # now upload to s3
         # requires S3 PutObject and PutObjectAcl permissions
         aws s3 cp $TMPLOCAL/$FILENAME.jpg $s3bucket/$DATEDIR/ \
-            --acl "public-read" 2>&1 | logger -i -t $loggertitle
+            --acl "public-read" 2>&1 | logger -t $loggertitle
 
         if [ ${PIPESTATUS[0]} -eq 0 ]; then
             aws s3 cp "$s3bucket/$DATEDIR/$FILENAME.jpg" "$s3bucket/current.jpg" \
-                --acl "public-read" 2>&1 | logger -i -t $loggertitle
+                --acl "public-read" 2>&1 | logger -t $loggertitle
         else
-            logger -i -t $loggertitle "[WARN] AWSCLI failed"
+            logger -t $loggertitle "[WARN] AWSCLI failed"
             if [ -f $TMPLOCAL/$FILENAME.jpg ]; then
                 echo "aws s3 cp $TMPLOCAL/$FILENAME.jpg $s3bucket/$DATEDIR/ --acl public-read" \
                     >> $maindir/aws-s3-cp-$RETRYDATE.retry
-                logger -i -t $loggertitle "[WARN] $maindir/aws-s3-cp-$RETRYDATE.retry file written"
+                logger -t $loggertitle "[WARN] $maindir/aws-s3-cp-$RETRYDATE.retry file written"
             else
-                logger -i -t $loggertitle "[WARN] File $TMPLOCAL/$FILENAME.jpg does not exist"
+                logger -t $loggertitle "[WARN] File $TMPLOCAL/$FILENAME.jpg does not exist"
             fi
         fi
     fi
diff --git a/etc/scripts/create-timelapse b/etc/scripts/create-timelapse
--- a/etc/scripts/create-timelapse
+++ b/etc/scripts/create-timelapse
@@ -5,7 +5,7 @@
 
 # dont do anything if process is already running
 if [ $(pgrep -f ${0} | wc -l) -gt 2 ]; then
-    echo "[WARN] Process of ${0} is already running"
+    echo "[ERR] Process of ${0} is already running"
     exit
 fi
 
@@ -15,10 +15,15 @@ if [ -z "$1" ]; then
 fi
 
 loggertitle="$(basename ${0})[$$]"
+
 CONFIG=$(cat /etc/rpi.json)
 CAM=${1,,} # always lower case ($1 param)
 if [ ! -z "$2" ]; then
     DATEDIR=$(date +%Y/%m/%d --date="$2")
+    if [ $? -ne 0 ]; then
+        logger -t $loggertitle "[ERR] Issues with date provided. Cannot continue."
+        exit
+    fi
     LAPSEFILE="${CAM}_$(date +%Y%m%d --date="$2").mp4"
 else
     DATEDIR=$(date +%Y/%m/%d --date="yesterday 13:00")
@@ -34,22 +39,34 @@ if [ ! -d $ALLJPEGS ]; then
 fi
 
 if [ ! -d $LAPSEDIR ]; then
-    mkdir -v -p $LAPSEDIR | logger -i -t $loggertitle
+    mkdir -v -p $LAPSEDIR | logger -t $loggertitle
+fi
+
+if [ "$3" == "forcefroms3" ]; then
+    # download everything from S3
+    s3bucket="s3://"$(jq -r .aws.s3 <<< $CONFIG)"/$CAM/$DATEDIR"
+    s3sync="aws s3 sync $s3bucket/ $ALLJPEGS/ --exclude=* --include=*.jpg"
+    logger -t $loggertitle "> $s3sync"
+    eval $s3sync
+    if [ $? -ne 0 ]; then
+        logger -t $loggertitle "[ERR] AWS CLI s3 sync failed. Cannot continue."
+        exit
+    fi
 fi
 
 # if we are here we are good to make a timelapse!
 ffmpeg="ionice -c2 -n 5 ffmpeg -r 24 -pattern_type glob -i \"$ALLJPEGS/*.jpg\" \
     -s hd1080 -vcodec libx264 -pix_fmt yuvj420p /tmp/$LAPSEFILE -y"
-logger -i -t $loggertitle "> $ffmpeg"
+logger -t $loggertitle "> $ffmpeg"
 
 eval $ffmpeg
 
 if [ ${PIPESTATUS[0]} -eq 0 ]; then
-    mv -fv /tmp/$LAPSEFILE $LAPSEDIR/$LAPSEFILE | logger -i -t $loggertitle
-    logger -i -t $loggertitle "[OK] $LAPSEDIR/$LAPSEFILE"
+    mv -fv /tmp/$LAPSEFILE $LAPSEDIR/$LAPSEFILE | logger -t $loggertitle
+    logger -t $loggertitle "[OK] $LAPSEDIR/$LAPSEFILE"
     # now wipe the dir!
-    rm -fr $ALLJPEGS 2>&1 | logger -i -t $loggertitle
+    rm -fr $ALLJPEGS 2>&1 | logger -t $loggertitle
 else
-    logger -i -t $loggertitle "[ERR] Failed to create $LAPSEDIR/$LAPSEFILE timelapse. FFMPEG exit code: $?"
-    rm -fv "/tmp/$LAPSEFILE" 2>&1 | logger -i -t $loggertitle
+    logger -t $loggertitle "[ERR] Failed to create $LAPSEDIR/$LAPSEFILE timelapse. FFMPEG exit code: $?"
+    rm -fv "/tmp/$LAPSEFILE" 2>&1 | logger -t $loggertitle
 fi
diff --git a/etc/scripts/get-ip b/etc/scripts/get-ip
--- a/etc/scripts/get-ip
+++ b/etc/scripts/get-ip
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+loggertitle="$(basename ${0})[$$]"
+
 CONFIG=$(cat /etc/rpi.json)
 maindir=$(jq -r .maindir <<< $CONFIG)
 aws_r53ttl=$(jq -r .aws.r53ttl <<< $CONFIG )
@@ -21,18 +23,18 @@ if [ ! -z "$privateIP" ] && [ ! -z "$publicIP" ]; then
     if [ "${publicIP}" != "${publicIP_previous}" ]; then
         echo $(printf $aws_r53json "$aws_r53subd" "$aws_r53ttl" "$publicIP") \
             > /tmp/get-ip-change-batch.json
-        cat /tmp/get-ip-change-batch.json | logger -t "get-ip Route53"
+        cat /tmp/get-ip-change-batch.json | logger -t $loggertitle
         aws route53 change-resource-record-sets --hosted-zone-id $aws_r53zoneid \
             --change-batch "file:///tmp/get-ip-change-batch.json" 2>&1 \
-            | awk '{print}' ORS='' | logger -t get-ip
+            | awk '{print}' ORS='' | logger -t $loggertitle
         if [ ${PIPESTATUS[0]} -ne 0 ]; then
-            logger -t get-ip "[ERROR] Could not set public IP address on $2! AWS Route53 exit code: $?"
+            logger -t $loggertitle "[ERR] Could not set public IP address on $2! AWS Route53 exit code: $?"
         else
             echo "{\"pri\":\"${privateIP}\",\"pub\":\"${publicIP}\"}" > $maindir/ip.json
-            cat $maindir/ip.json | logger -t "get-ip $maindir/ip.json"
+            cat $maindir/ip.json | logger -t $loggertitle "$maindir/ip.json"
             rm -vf /tmp/get-ip-change-batch.json
         fi
     fi
 else
-    logger -t get-ip "[WARN] Could not determine private or public IP address!"
+    logger -t $loggertitle "[ERR] Could not determine private or public IP address!"
 fi
diff --git a/etc/scripts/sunset-sunrise-today b/etc/scripts/sunset-sunrise-today
--- a/etc/scripts/sunset-sunrise-today
+++ b/etc/scripts/sunset-sunrise-today
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-# set this to your own location
-maindir=$(cat /etc/rpi.json | jq -r .maindir)
-sunapi=$(cat /etc/rpi.json | jq -r .sun.api)
+loggertitle="$(basename ${0})[$$]"
+
+CONFIG=$(cat /etc/rpi.json)
+maindir=$(jq -r .maindir <<< $CONFIG)
+sunapi=$(jq -r .sun.api <<< $CONFIG)
 out="$maindir/sunrise-sunset-today.json"
 
 if [ ! -d $maindir ]; then
@@ -15,7 +17,7 @@ curl -m 10 -s -f "$sunapi" -o $out
 if [ $? -eq 0 ]; then
     echo "$out written"
 else
-    logger -t sunrise-sunset-today "[WARN] Failed update $out file. CURL exit code: $?"
+    logger -t $loggertitle "[WARN] Failed update $out file. CURL exit code: $?"
 fi
 
-cat $out | logger -t sunrise-sunset-today
+cat $out | logger -t $loggertitle
